# Generated by Django 3.1.6 on 2021-05-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeblocker', '0004_auto_20210513_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleuser',
            name='token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
