# Generated by Django 3.1.6 on 2021-05-12 18:06

from django.db import migrations
import oauth2client.contrib.django_util.models


class Migration(migrations.Migration):

    dependencies = [
        ('timeblocker', '0002_auto_20210509_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleuser',
            name='credentials',
            field=oauth2client.contrib.django_util.models.CredentialsField(null=True),
        ),
    ]
